version: "3"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # logging:
    #   options:
    #     max-size: 10m
    #     max-file: "3"
    ports:
      - '5438:5432'
    networks:
      - gen-ai-net
    volumes: 
      - ./db_migration/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./db_migration/tables_schema.sql:/docker-entrypoint-initdb.d/create_tables.sql

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
  #     PGADMIN_DEFAULT_PASSWORD: strong-password
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

  # web:
  #   build: ./my-app
  #   ports:
  #     - 8000:8000
  #   # volumes:
  #   #   - ./my-app:/app
  #   networks:
  #     - gen-ai-net
  #   depends_on:
  #     postgres:
  #       condition: service_started
  #     ollama: 
  #       condition: service_started
      
  ollama:
    build: ollama
    ports:
      - 11434:11434
    networks:
      - gen-ai-net
    volumes:
      - ./ollama_model:/ollama
    # networks:
    #   - tutorial-net
    entrypoint: ["/usr/bin/bash", "/pull_model.sh"]

networks:
  gen-ai-net:
    driver: bridge

# volumes:
#   tutorial-vol:
#     driver: local
  
  # local_pgdata:
  # pgadmin-data: