version: "3"

services:

  db:
    hostname: postgres
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  web:
    build: ./my-app
    ports:
      - 8000:8000
    volumes:
      - ./my-app:/app
    networks:
      - tutorial-net
  ollama:
    build: ollama
    ports:
      - 11434:11434
    volumes:
      - tutorial-vol:/ollama
    networks:
      - tutorial-net
    entrypoint: ["/usr/bin/bash", "/pull_model.sh"]

networks:
  tutorial-net:
    driver: bridge

volumes:
  tutorial-vol:
    driver: local
  
  local_pgdata:
  pgadmin-data: